<?php

// autoload_psr4.php @generated by Composer

$vendorDir = dirname(dirname(__FILE__));
$baseDir = dirname(dirname($vendorDir));

return array(
    'RingCentral\\Psr7\\' => array($vendorDir . '/ringcentral/psr7/src'),
    'React\\Stream\\' => array($vendorDir . '/react/stream/src'),
    'React\\Socket\\' => array($vendorDir . '/react/socket/src'),
    'React\\Promise\\Timer\\' => array($vendorDir . '/react/promise-timer/src'),
    'React\\Promise\\Stream\\' => array($vendorDir . '/react/promise-stream/src'),
    'React\\Promise\\' => array($vendorDir . '/react/promise/src'),
    'React\\Http\\' => array($vendorDir . '/react/http/src'),
    'React\\EventLoop\\' => array($vendorDir . '/react/event-loop/src'),
    'React\\Dns\\' => array($vendorDir . '/react/dns/src'),
    'React\\Cache\\' => array($vendorDir . '/react/cache/src'),
    'Psr\\Http\\Message\\' => array($vendorDir . '/psr/http-message/src'),
    'OC\\Settings\\' => array($baseDir . '/settings'),
    'OC\\Core\\' => array($baseDir . '/core'),
    'OC\\' => array($baseDir . '/lib/private'),
    'OCP\\' => array($baseDir . '/lib/public'),
    'JakubOnderka\\PhpConsoleColor\\' => array($vendorDir . '/jakub-onderka/php-console-color/src'),
);
